
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 72
#define YY_END_OF_BUFFER 73
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[190] =
    {   0,
       64,   64,    0,    0,    0,    0,    0,    0,   73,   71,
       70,    1,   27,   40,   21,   26,   69,   28,   29,   20,
       34,   20,   64,   21,   18,   35,   23,   24,   23,   39,
       39,   32,   33,   26,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   30,   26,   31,   55,   53,   55,
       54,   55,   59,   58,   59,   59,   61,   62,   61,   61,
       70,   23,   25,   69,   69,   69,   68,    0,   69,   22,
       64,   19,   66,   65,   60,   56,   19,   18,   65,   26,
       39,   65,   65,   39,   39,   39,   39,   39,   39,    4,
       39,   39,   39,    2,   39,   39,   39,   39,   39,   53,

       52,    0,   45,   44,   51,   43,   46,   49,   47,   41,
       48,   42,   50,   58,   57,    0,   62,   63,    0,   37,
       37,    0,   36,    0,   65,   64,   64,   19,   65,   65,
       19,   65,   64,   39,   39,   39,   39,   39,   39,   39,
       39,    3,    5,   39,   39,   39,   39,   67,   38,   38,
       65,   19,   64,   65,   65,   19,   39,   16,   13,   39,
       39,   39,   10,   39,   39,   39,    7,   39,   19,   65,
       64,   12,   39,   39,   39,    6,   39,   39,   11,   64,
       39,   39,   14,   15,    8,   39,    9,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,   29,   24,    1,   30,   31,   32,   33,

       34,   35,   24,   36,   37,   24,   38,   39,   24,   40,
       41,   24,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[51] =
    {   0,
        1,    1,    2,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    3,    3,    1,
        1,    1,    1,    3,    3,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[197] =
    {   0,
        0,    0,   48,   52,   56,   58,   60,   62,  373,  374,
       65,  374,  350,  374,  374,  363,   67,  374,  374,  357,
      374,  354,   70,   65,   74,  374,   59,  346,   74,  351,
       87,  374,  374,  374,   68,   82,   37,  327,   75,   85,
       93,   91,   95,   97,  374,  316,  374,  374,  374,  361,
      374,  136,  374,  374,  360,  118,  374,  374,  359,  344,
      113,  374,  374,  351,  374,  350,  349,  348,  177,  374,
      110,  112,    0,  134,  374,  374,  139,    0,  146,  374,
      340,  154,  169,  119,  135,  125,  144,  103,  140,  132,
      163,  168,  173,  338,  174,  176,  165,  177,  185,  374,

      374,  336,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  335,  374,  374,  327,  374,
      374,  326,  374,  324,  181,  190,  208,  212,  216,  220,
      198,  225,  229,  221,  182,  213,  181,  224,  230,  233,
      234,  316,  315,  236,  240,  237,  241,  374,  374,  374,
      244,  250,    0,  258,  256,  267,  249,  314,  312,  242,
      243,  262,  310,  266,  273,  274,  309,  275,  276,  280,
      284,  308,  277,  281,  288,  307,  289,  291,  305,  295,
      292,  296,  303,  302,  194,  300,  175,  108,  374,  340,
      343,  346,  349,   65,   54,  352

    } ;

static const flex_int16_t yy_def[197] =
    {   0,
      189,    1,  190,  190,  191,  191,  192,  192,  189,  189,
      189,  189,  189,  189,  189,  189,  193,  189,  189,  189,
      189,  189,  194,  189,  194,  189,  189,  189,  189,  195,
      195,  189,  189,  189,  195,  195,  195,   31,  195,  195,
      195,  195,  195,  195,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  196,  189,  189,  189,  196,  196,  189,
      194,   71,  194,  194,  189,  189,   25,   25,  194,  189,
      195,  189,  194,   31,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  196,  189,
      189,  189,  189,  196,   74,   74,  194,   25,  189,  194,
       79,  189,  189,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  189,  189,  189,
      189,  194,  127,   79,  189,  189,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  189,  189,
      194,  195,  195,  195,  195,  195,  195,  195,  195,  189,
      195,  195,  195,  195,  195,  195,  195,  195,    0,  189,
      189,  189,  189,  189,  189,  189

    } ;

static const flex_int16_t yy_nxt[425] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   15,   20,   21,   22,   23,   24,   25,   25,   26,
       27,   28,   29,   30,   31,   32,   10,   33,   34,   30,
       35,   36,   37,   38,   39,   30,   40,   30,   30,   30,
       30,   41,   42,   30,   30,   43,   44,   45,   46,   47,
       49,   50,   73,   51,   49,   50,   81,   51,   54,   55,
       54,   55,   58,   59,   58,   59,   61,   73,   61,   65,
       89,   60,   66,   60,   52,   67,   75,   90,   52,   80,
       62,   76,   56,   73,   56,   71,   68,   72,   72,   77,
       73,   78,   78,   69,   74,   62,   80,   73,   79,   82,

       73,   82,   83,   74,   84,   84,   73,   79,   73,   85,
       73,   86,   73,   92,   61,   93,   61,   87,   73,   94,
      115,  116,   88,   73,   95,   71,   96,   71,   71,   72,
       72,  189,   99,  189,   74,   98,  125,   97,  101,  102,
       73,  103,  137,   74,  104,  125,   82,   73,   82,   83,
       73,  126,  126,  105,  127,   73,  128,  128,  129,   73,
      129,  130,  106,  131,  131,  107,  108,  135,  134,  132,
      109,  133,  133,  136,  138,  110,  139,  111,   73,  112,
       73,  113,  122,   73,   83,  123,   83,   83,   73,   73,
       73,   73,   73,  151,  124,  151,   73,   73,  152,  152,

       73,  145,  189,  124,  189,  140,  124,  124,  141,   73,
      189,  124,  189,  146,  142,  158,  124,  143,  124,  144,
      124,  147,  124,  127,  160,  153,  153,  127,   73,  128,
      128,  155,  154,  156,  156,  130,   73,  130,  130,   73,
      132,  154,  132,  132,  132,   73,  133,  133,   73,   73,
      157,   73,   73,  161,  159,   73,   73,   73,   73,  132,
      162,  169,  169,  164,   73,   83,  163,  152,  152,  167,
      170,  155,  170,  155,  155,  171,  171,   73,  173,  168,
      165,   73,  155,  166,  156,  156,  172,  174,   73,   73,
       73,  132,   73,  169,  169,  155,   73,  180,  180,  130,

      175,  171,  171,   73,   73,  178,   73,   73,  179,  176,
      155,   73,  180,  180,  177,   73,  181,   73,   73,  182,
       73,  183,   73,   73,   73,   73,  185,   73,  184,   73,
       73,   73,  150,  188,  149,  148,  186,  115,  101,  187,
       48,   48,   48,   53,   53,   53,   57,   57,   57,   64,
       64,   64,  119,   73,  119,   73,  120,  121,  121,  120,
      118,  117,  114,  100,   63,   91,   73,   62,   70,   70,
       63,   62,  189,    9,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189
    } ;

static const flex_int16_t yy_chk[425] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,   37,    3,    4,    4,  195,    4,    5,    5,
        6,    6,    7,    7,    8,    8,   11,  194,   11,   17,
       37,    7,   17,    8,    3,   17,   24,   37,    4,   27,
       27,   24,    5,   35,    6,   23,   17,   23,   23,   25,
       39,   25,   25,   17,   23,   29,   29,   36,   25,   31,

       40,   31,   31,   23,   31,   31,   42,   25,   41,   35,
       43,   36,   44,   39,   61,   39,   61,   36,   88,   40,
       56,   56,   36,  188,   40,   71,   41,   71,   71,   72,
       72,   84,   44,   84,   71,   43,   72,   42,   52,   52,
       86,   52,   88,   71,   52,   72,   74,   90,   74,   74,
       85,   74,   74,   52,   77,   89,   77,   77,   79,   87,
       79,   79,   52,   79,   79,   52,   52,   86,   85,   82,
       52,   82,   82,   87,   89,   52,   90,   52,   91,   52,
       97,   52,   69,   92,   83,   69,   83,   83,   93,   95,
      187,   96,   98,  125,   69,  125,  137,  135,  125,  125,

       99,   97,  126,   69,  126,   91,   69,   69,   92,  185,
      131,   69,  131,   98,   93,  135,   69,   95,   69,   96,
       69,   99,   69,  127,  137,  127,  127,  128,  136,  128,
      128,  129,  127,  129,  129,  130,  134,  130,  130,  138,
      132,  127,  132,  132,  133,  139,  133,  133,  140,  141,
      134,  144,  146,  138,  136,  145,  147,  160,  161,  151,
      139,  151,  151,  141,  157,  152,  140,  152,  152,  146,
      154,  155,  154,  155,  155,  154,  154,  162,  160,  147,
      144,  164,  156,  145,  156,  156,  157,  161,  165,  166,
      168,  169,  173,  169,  169,  170,  174,  170,  170,  171,

      162,  171,  171,  175,  177,  166,  178,  181,  168,  164,
      180,  182,  180,  180,  165,  186,  173,  184,  183,  174,
      179,  175,  176,  172,  167,  163,  178,  159,  177,  158,
      143,  142,  124,  186,  122,  119,  181,  116,  102,  182,
      190,  190,  190,  191,  191,  191,  192,  192,  192,  193,
      193,  193,  196,   94,  196,   81,   68,   67,   66,   64,
       60,   59,   55,   50,   46,   38,   30,   28,   22,   20,
       16,   13,    9,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1905047.l"



#line 6 "1905047.l"
#include<stdio.h>
#include<iostream>
#include<stdlib.h>
#include<iterator>
#include<string>
#include<vector>
#include<fstream>
using namespace std;

int errorCount=0;
int line_count=1;
int temp_line_count=0;

FILE *logout;
FILE *tokenout;

using namespace std;

class symbolInfo{
    private:
        string symbolName;
        string symbolType;
        symbolInfo* nextSymbolInfo;
        
    public:
  
        symbolInfo(string symbolName,string symbolType){
            this->symbolName=symbolName;
            this->symbolType=symbolType;
            nextSymbolInfo=NULL;
        }    

        void setSymbolName(string symbolName){
            this->symbolName=symbolName;
        }
        

        string getSymbolName(){
            return symbolName;
        }

        void setSymbolType(string symbolType){
            this->symbolType=symbolType;
        }

        string getsymbolType(){
            return symbolType;
        }

        void setnextSymbolInfo(symbolInfo* nextElement){
            nextSymbolInfo=nextElement;
        }

        symbolInfo* getnextSymbolInfo(){
            return nextSymbolInfo;
        }
};

class scopeTable{
    private:
        symbolInfo** hashTable;
        scopeTable* parentScopeTable;
        int scopeTableId;
        int numBucket;
    public:
        scopeTable(int n,scopeTable* parentScopeTable,int scopeTableId){
            hashTable=new symbolInfo*[n];
            this->parentScopeTable=parentScopeTable;
            numBucket=n;
            this->scopeTableId=scopeTableId;

            for(int i=0;i<n;i++){
                hashTable[i]=nullptr;
            }
            //cout<<"ScopeTable# "<<scopeTableId<<" created"<<endl;
        } 

        ~scopeTable(){
            for(int i=0;i<numBucket;i++){
                delete hashTable[i];
            }
            delete[] hashTable;
        }

        int getScopeTableId(){
            return scopeTableId;
        }

        int getNumBucket(){
            return numBucket;
        }

        scopeTable* getParentScopeTable(){
            return parentScopeTable;
        }

     unsigned int SDBMHash(string symbolName) {
	        unsigned int hash = 0;
	        unsigned int i = 0;
	        unsigned int len = symbolName.length();

	        for (i = 0; i < len; i++){
		        hash = ((symbolName[i]) + (hash << 6) + (hash << 16) - hash)%numBucket;
	        }

	        return hash;
        }

    symbolInfo* lookUp(string symbolName){
        int bucketNo=SDBMHash(symbolName)%numBucket;
        symbolInfo* symbolInfoPtr=hashTable[bucketNo];

        int i=1;
        while(symbolInfoPtr){
            if(symbolInfoPtr->getSymbolName()==symbolName){
                //cout<<"'"<<symbolName<<"'"<<" found in ScopeTable# "<<scopeTableId<<" at position "<<bucketNo+1<<", "<<i<<endl;
                return symbolInfoPtr;
            }
            symbolInfoPtr=symbolInfoPtr->getnextSymbolInfo();
            i++;
        }
        return nullptr;
    }

    bool insert(symbolInfo symbol){
        string symbolName=symbol.getSymbolName();
        
        
        int bucketNo=SDBMHash(symbolName)%numBucket;
        symbolInfo* symbolInfoPtr=hashTable[bucketNo];
        
        //check if already exist
        int i=0;
        bool flag=false;
        while(symbolInfoPtr){
            if(symbolInfoPtr->getSymbolName()==symbolName){
                flag=true;
                break;
            }
            
            symbolInfoPtr=symbolInfoPtr->getnextSymbolInfo();
            i++;
        }

        if(flag){
            //cout<<"'"<<symbolName<<"'"<<" already exists in the current ScopeTable"<<endl;
            return false;
        }

        symbolInfoPtr=hashTable[bucketNo];


        if(symbolInfoPtr==nullptr){
            hashTable[bucketNo]=new symbolInfo(symbol.getSymbolName(),symbol.getsymbolType());
            //cout<<"Inserted in ScopeTable# "<<scopeTableId<<" at position "<<bucketNo+1<<", 1"<<endl;
        }
        else{
            int i=2;
            while(symbolInfoPtr->getnextSymbolInfo()){
                i++;
                symbolInfoPtr=symbolInfoPtr->getnextSymbolInfo();
            }
            symbolInfo* symbolInfoInserted=new symbolInfo(symbol.getSymbolName(),symbol.getsymbolType());
            symbolInfoPtr->setnextSymbolInfo(symbolInfoInserted);
            //cout<<"Inserted in ScopeTable# "<<scopeTableId<<" at position "<<bucketNo+1<<", "<<i<<endl;

        }
        return true;
    }

    bool Delete(string symbolName){
        int bucketNo=SDBMHash(symbolName)%numBucket;

        symbolInfo* symbolInfoPtr=hashTable[bucketNo];
        symbolInfo* prevSymbolInfo=nullptr;

        int i=1;
        while(symbolInfoPtr){

            if(symbolInfoPtr->getSymbolName()==symbolName){
                //cout<<"Deleted "<<"'"<<symbolName<<"'"<<" from ScopeTable# "<<scopeTableId<<" at position "<<bucketNo+1<<", "<<i<<endl;

                if(!prevSymbolInfo){
                    hashTable[bucketNo]=symbolInfoPtr->getnextSymbolInfo();
                }
                else{
                    prevSymbolInfo->setnextSymbolInfo(symbolInfoPtr->getnextSymbolInfo());
                }
                delete symbolInfoPtr;
                return true;
            }

            i++;
            prevSymbolInfo=symbolInfoPtr;
            symbolInfoPtr=symbolInfoPtr->getnextSymbolInfo();
        }
        //cout<<"Not found in the current ScopeTable"<<endl;
        return false;
    }

    void print(){
        fprintf(logout,"\t");
        //cout<<"\t";
        fprintf(logout,"ScopeTable# %d",scopeTableId);
         fprintf(logout,"\n");
        //cout<<"ScopeTable# "<<scopeTableId<<endl;

        for(int i=1;i<=numBucket;i++){  
            symbolInfo* symbolInfoPtr=hashTable[i-1];
            if(!symbolInfoPtr) continue; 
            fprintf(logout,"\t");
            //cout<<"\t";
            //cout<<i<<"--> ";
            fprintf(logout,"%d--> ",i);
            while(symbolInfoPtr){
                fprintf(logout,"<%s,%s> ",symbolInfoPtr->getSymbolName().c_str(),symbolInfoPtr->getsymbolType().c_str());
                //cout<<"<"<<symbolInfoPtr->getSymbolName()<<","<<symbolInfoPtr->getsymbolType()<<"> ";
                symbolInfoPtr=symbolInfoPtr->getnextSymbolInfo();
            }
            fprintf(logout,"\n");
            //cout<<endl;
        }
    }
};

    

class symbolTable{
    private:
        scopeTable* currentScopeTable;
        int currentScopeTableSize;
        static int scopeTableCount;
        static bool isEmpty;
    
    public:
        symbolTable(int currentScopeTableSize){
            this->currentScopeTableSize=currentScopeTableSize;
            currentScopeTable=new scopeTable(currentScopeTableSize,nullptr,++scopeTableCount);    
        }

        void enterScope(){
            scopeTable* temp=new scopeTable(currentScopeTableSize,currentScopeTable,++scopeTableCount);
            currentScopeTable=temp;
        }

        void exitScope(string command){
            if(currentScopeTable->getScopeTableId()==1 && command!="Q"){
                //cout<<"ScopeTable# 1 cannot be removed"<<endl;
                return;
            }
            if(currentScopeTable->getScopeTableId()==1){
                isEmpty=true;
            }
            scopeTable* temp=currentScopeTable;
            currentScopeTable=currentScopeTable->getParentScopeTable();
            //cout<<"ScopeTable# "<<temp->getScopeTableId()<<" removed"<<endl;
            delete temp;
        }

        bool insert(symbolInfo symbol){
            bool retValue=currentScopeTable->insert(symbol);
            return retValue;
        }

        bool remove(string symbolName){
            bool retValue=currentScopeTable->Delete(symbolName);
            return retValue;
        }

        symbolInfo* lookup(string symbolName){
            scopeTable* scopeTablePtr=currentScopeTable;

            while(scopeTablePtr){
                symbolInfo* foundScopeTable=scopeTablePtr->lookUp(symbolName);
                if(foundScopeTable){
                    return foundScopeTable;
                }
                else{
                    scopeTablePtr=scopeTablePtr->getParentScopeTable();
                }
            }
            //cout<<"'"<<symbolName<<"'"<<" not found in any of the ScopeTables"<<endl;
            return nullptr;
        }

        void printCurrentScope(){
            currentScopeTable->print();
        }

        void printAllScope(){
            scopeTable* scopeTablePtr=currentScopeTable;
            while(scopeTablePtr){
                scopeTablePtr->print();
                scopeTablePtr=scopeTablePtr->getParentScopeTable();
            }
        }

        static int getScopeTableCount(){
            return scopeTableCount;
        }

        static bool getIsEmpty(){
            return isEmpty;
        }
};

int symbolTable::scopeTableCount=0;
bool symbolTable::isEmpty=false;

symbolTable symbolTableObj(10);

string tokenStr,logStr,strLexemeType,logComment,commentLexemeType;
#line 917 "lex.yy.c"
#line 918 "lex.yy.c"

#define INITIAL 0
#define STRING_STATE 1
#define SINGLE_LINE_COMMENT_STATE 2
#define MULTI_LINE_COMMENT_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 353 "1905047.l"


#line 1141 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 190 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 374 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 355 "1905047.l"
{
			line_count++;
		}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 359 "1905047.l"
{
			fprintf(tokenout,"<IF, if>\n");
			fprintf(logout,"Line# %d: Token <IF> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 364 "1905047.l"
{
			fprintf(tokenout,"<FOR, for>\n");
			fprintf(logout,"Line# %d: Token <FOR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 368 "1905047.l"
{
			fprintf(tokenout,"<DO, do>\n");
			fprintf(logout,"Line# %d: Token <DO> Lexeme %s found\n",line_count,yytext);

		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 373 "1905047.l"
{
			fprintf(tokenout,"<INT, int>\n");
			fprintf(logout,"Line# %d: Token <INT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 377 "1905047.l"
{
			fprintf(tokenout,"<FLOAT, float>\n");
			fprintf(logout,"Line# %d: Token <FLOAT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 381 "1905047.l"
{	
			fprintf(tokenout,"<VOID, void>\n");
			fprintf(logout,"Line# %d: Token <VOID> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 386 "1905047.l"
{
			fprintf(tokenout,"<SWITCH, switch>\n");
			fprintf(logout,"Line# %d: Token <SWITCH> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 390 "1905047.l"
{
			fprintf(tokenout,"<DEFAULT, default>\n");
			fprintf(logout,"Line# %d: Token <DEFAULT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 394 "1905047.l"
{
			fprintf(tokenout,"<ELSE, else>\n");
			fprintf(logout,"Line# %d: Token <ELSE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 398 "1905047.l"
{
			fprintf(tokenout,"<WHILE, while>\n");
			fprintf(logout,"Line# %d: Token <WHILE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 402 "1905047.l"
{
			fprintf(tokenout,"<BREAK, break>\n");
			fprintf(logout,"Line# %d: Token <BREAK> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 406 "1905047.l"
{
			fprintf(tokenout,"<CHAR, char>\n");
			fprintf(logout,"Line# %d: Token <CHAR> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 410 "1905047.l"
{
			fprintf(tokenout,"<DOUBLE, double>\n");
			fprintf(logout,"Line# %d: Token <DOUBLE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 414 "1905047.l"
{
			fprintf(tokenout,"<RETURN, return>\n");
			fprintf(logout,"Line# %d: Token <RETURN> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 418 "1905047.l"
{
			fprintf(tokenout,"<CASE, case>\n");
			fprintf(logout,"Line# %d: Token <CASE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 422 "1905047.l"
{
			fprintf(tokenout,"<CONTINUE, continue>\n");
			fprintf(logout,"Line# %d: Token <CONTINUE> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 426 "1905047.l"
{		
			fprintf(tokenout,"<CONST_INT, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <CONST_INT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 430 "1905047.l"
{
			fprintf(tokenout,"<CONST_FLOAT, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <CONST_FLOAT> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 434 "1905047.l"
{
			fprintf(tokenout,"<ADDOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <ADDOP> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 438 "1905047.l"
{
			fprintf(tokenout,"<MULOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <MULOP> Lexeme %s found\n",line_count,yytext);		
		}	
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 442 "1905047.l"
{
			fprintf(tokenout,"<INCOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <INCOP> Lexeme %s found\n",line_count,yytext);		
		}						
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 446 "1905047.l"
{
			fprintf(tokenout,"<RELOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RELOP> Lexeme %s found\n",line_count,yytext);
		}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 450 "1905047.l"
{
			fprintf(tokenout,"<ASSIGNOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <ASSIGNOP> Lexeme %s found\n",line_count,yytext);		
		}	
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 454 "1905047.l"
{
			fprintf(tokenout,"<LOGICOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LOGICOP> Lexeme %s found\n",line_count,yytext);		
		}	
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 458 "1905047.l"
{
			fprintf(tokenout,"<BITOP, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <BITOP> Lexeme %s found\n",line_count,yytext);		
		}	
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 462 "1905047.l"
{
			fprintf(tokenout,"<NOT, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <NOT> Lexeme %s found\n",line_count,yytext);		
		}	
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 466 "1905047.l"
{
			fprintf(tokenout,"<LPAREN, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LPAREN> Lexeme %s found\n",line_count,yytext);		
		}	
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 470 "1905047.l"
{
			fprintf(tokenout,"<RPAREN, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RPAREN> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 474 "1905047.l"
{
            symbolTableObj.enterScope();
			fprintf(tokenout,"<LCURL, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LCURL> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 479 "1905047.l"
{
            symbolTableObj.exitScope("E");
			fprintf(tokenout,"<RCURL, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RCURL> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 484 "1905047.l"
{
			fprintf(tokenout,"<LSQUARE, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <LSQUARE> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 488 "1905047.l"
{
			fprintf(tokenout,"<RSQUARE, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <RSQUARE> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 492 "1905047.l"
{
			fprintf(tokenout,"<COMMA, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <COMMA> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 496 "1905047.l"
{
			fprintf(tokenout,"<SEMICOLON, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <SEMICOLON> Lexeme %s found\n",line_count,yytext);		
		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 500 "1905047.l"
{
            errorCount++;
            fprintf(logout,"Error at line# %d: UNFINISHED_CONST_CHAR %s\n", line_count ,yytext);
        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 504 "1905047.l"
{
            string character="";
            character+=yytext[1];
			fprintf(tokenout,"<CONST_CHAR, %s>\n",character.c_str());
			fprintf(logout,"Line# %d: Token <CONST_CHAR> Lexeme %s found\n",line_count,character.c_str());
		}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 510 "1905047.l"
{
            string character="";

            if( yytext[2] =='n') character = '\n';
			else if( yytext[2] =='t') character = '\t';
			else if( yytext[2] =='a') character = '\a';
			else if( yytext[2] =='f') character = '\f';
			else if( yytext[2] =='r') character = '\r';
			else if( yytext[2] =='b') character = '\b';
			else if( yytext[2] =='v') character = '\v';
			else if( yytext[2] =='0') character = '\0';
			else if( yytext[2] =='\\') character = '\\';
			else character = '\"';
			fprintf(tokenout,"<CONST_CHAR, %s>\n",character.c_str());
			fprintf(logout,"Line# %d: Token <CONST_CHAR> Lexeme %s found\n",line_count,character.c_str());
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 527 "1905047.l"
{
            
			fprintf(tokenout,"<ID, %s>\n",yytext);
			fprintf(logout,"Line# %d: Token <ID> Lexeme %s found\n",line_count,yytext);

            bool checkExistance=symbolTableObj.insert(symbolInfo(yytext,"ID"));
            if(!checkExistance){
                fprintf(logout,"\t%s already exisits in the current ScopeTable\n",yytext);
            }
            else{
            symbolTableObj.printAllScope();
            }
		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 540 "1905047.l"
{
           tokenStr="";
           logStr="\"";
           temp_line_count=0;
           BEGIN STRING_STATE;
        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 546 "1905047.l"
{
           logStr+="\\n";
           tokenStr+="\n";
        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 550 "1905047.l"
{
            logStr+="\\t";
            tokenStr+="\t";
        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 554 "1905047.l"
{
            logStr+="\\\\";
            tokenStr+="\\";
        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 558 "1905047.l"
{
            logStr+="\\\'";
            tokenStr+="\'";
        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 562 "1905047.l"
{
            logStr+="\\\"";
            tokenStr+="\"";
        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 566 "1905047.l"
{
            logStr+="\\a";
            tokenStr+="\a";
        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 570 "1905047.l"
{
            logStr+="\\f";
            tokenStr+="\f";
        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 574 "1905047.l"
{
            logStr+="\\r";
            tokenStr+="\r";
        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 578 "1905047.l"
{
            logStr+="\\b";
            tokenStr+="\b";
        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 582 "1905047.l"
{
            logStr+="\\v";
            tokenStr+="\v";
        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 586 "1905047.l"
{
            logStr+="\\0";
            tokenStr+="\0";
        }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 590 "1905047.l"
{
            //multiline string
            temp_line_count++;
            string temp(yytext);
            logStr+=temp;
        }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 596 "1905047.l"
{
            temp_line_count++;
            errorCount++;
            fprintf(logout,"Error at line# %d: UNFINISHED_STRING %s\n", line_count ,logStr.c_str());
            line_count+=temp_line_count;
            temp_line_count=0;
            logStr="";
            tokenStr="";
            BEGIN INITIAL;
        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 606 "1905047.l"
{
            if(logStr.find("\n")!=string::npos){
                strLexemeType="MULTI LINE STRING";
            }
            else{
                strLexemeType="SINGLE LINE STRING";
            }
            logStr+="\"";
            fprintf(tokenout,"<%s, %s>\n",strLexemeType.c_str(),tokenStr.c_str());
            fprintf(logout,"Line# %d: Token <%s> Lexeme %s found\n",line_count,strLexemeType.c_str(),logStr.c_str());
            line_count+=temp_line_count;
            temp_line_count=0;
            logStr="";
            tokenStr="";
            BEGIN INITIAL;
        }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 622 "1905047.l"
{
            logStr+=yytext;
            tokenStr+=yytext;
        }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 627 "1905047.l"
{
            logComment="//";
            temp_line_count=0;
            BEGIN SINGLE_LINE_COMMENT_STATE;
        }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 632 "1905047.l"
{
            //multiple single line comment with a slash and a enter
            temp_line_count++;
            string temp(yytext);
            logComment+=temp;
        }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 638 "1905047.l"
{
            //single line comment without a slash at end(end of a single line comment)
            temp_line_count++;
            fprintf(logout,"Line# %d: Token <SINGLE LINE COMMENT> Lexeme %s found\n",line_count,logComment.c_str());
            line_count+=temp_line_count;
            logComment="";
            temp_line_count=0;
            BEGIN INITIAL;
        }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 647 "1905047.l"
{
            logComment+=yytext;
        }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 650 "1905047.l"
{
            logComment="/*";
            temp_line_count=0;
            BEGIN MULTI_LINE_COMMENT_STATE;
        }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 655 "1905047.l"
{
            string temp(yytext);
            logComment+=temp;
        }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 659 "1905047.l"
{
            //new line of the multiline comment
            string temp(yytext);
            logComment+=temp;
            temp_line_count++;
        }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 665 "1905047.l"
{
            //end of multiline comment
            string temp(yytext);
            logComment+=temp;
            fprintf(logout,"Line# %d: Token <MULTI LINE COMMENT> Lexeme %s found\n",line_count,logComment.c_str());
            line_count+=temp_line_count;
            logComment="";
            temp_line_count=0;
            BEGIN INITIAL;
        }
	YY_BREAK
case YY_STATE_EOF(MULTI_LINE_COMMENT_STATE):
#line 675 "1905047.l"
{
            //unfinished comment
            errorCount++;
            temp_line_count++;
            line_count+=temp_line_count;
            fprintf(logout,"Error at line# %d: UNFINISHED_COMMENT %s\n", line_count ,logComment.c_str());
            logComment="";
            temp_line_count=0;
            BEGIN INITIAL;
        }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 685 "1905047.l"
{
            errorCount++;
            fprintf(logout,"Error at line# %d: TOO_MANY_DECIMAL_POINTS %s\n", line_count ,yytext);
        }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 689 "1905047.l"
{
            errorCount++;
            fprintf(logout,"Error at line# %d: ILLFORMED_NUMBER %s\n", line_count ,yytext);
        }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 693 "1905047.l"
{
            errorCount++;
            fprintf(logout,"Error at line# %d: INVALID_ID_SUFFIX_NUM_PREFIX %s\n", line_count ,yytext);
        }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 697 "1905047.l"
{
            errorCount++;
            fprintf(logout,"Error at line# %d: MULTICHAR_CONST_CHAR %s\n", line_count ,yytext);
        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 701 "1905047.l"
{
            errorCount++;
            fprintf(logout,"Error at line# %d: EMPTY_CONST_CHAR %s\n", line_count ,yytext);
        }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 705 "1905047.l"
{
            errorCount++;
            fprintf(logout,"Error at line# %d: UNFINISHED_CONST_CHAR %s\n", line_count ,yytext);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 710 "1905047.l"
{}  
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 712 "1905047.l"
{
    errorCount++;
    fprintf(logout,"Error at line# %d: UNRECOGNIZED_CHAR %s\n", line_count ,yytext);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 717 "1905047.l"
ECHO;
	YY_BREAK
#line 1851 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING_STATE):
case YY_STATE_EOF(SINGLE_LINE_COMMENT_STATE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 190 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 190 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 189);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 717 "1905047.l"


int main(int argc, char** argv) {
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	
	logout= fopen("log.txt","w");
	tokenout= fopen("token.txt","w");

	yyin= fin;
	yylex();
	fclose(yyin);
    symbolTableObj.printAllScope();
    fprintf(logout,"Total lines: %d\n",line_count);
    fprintf(logout,"Total errors: %d",errorCount);
	fclose(tokenout);
	fclose(logout);
	return 0;
}

